# Generated by Django 3.0 on 2020-01-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_media_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='media_training',
            name='title_of_media',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='media_training',
            name='instruction',
            field=models.CharField(max_length=2000),
        ),
    ]
