# Generated by Django 3.0 on 2020-01-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200104_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='media_training',
            name='videofile',
            field=models.FileField(null=True, upload_to='', verbose_name=''),
        ),
    ]
