# Generated by Django 3.0 on 2020-01-16 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200116_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media_training',
            name='videofile',
        ),
        migrations.CreateModel(
            name='media_training_video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_media', models.CharField(default='', max_length=200)),
                ('instruction', models.CharField(default='', max_length=2000)),
                ('videofile', models.FileField(null=True, upload_to='')),
                ('pub_create', models.DateTimeField(verbose_name='date de création')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Apps')),
            ],
        ),
    ]
